### ISSUE TITLE
您好，可否告知云数据库的相关表设置

### ISSUE THREAD

**Issue by Rock-L21** [GritJack/Wapp#8]
在部署您的小程序的时候，发现云数据库的集合及属性是未知的，想问一下您的小程序数据库格式是怎么样的，此番目的仅仅是为了完成老师的期末课程设计，并无商用之意。

**Comment by Rem0uld** [comment]
![image](https://user-images.githubusercontent.com/49944064/102691977-53275880-424b-11eb-818d-fd06b41feb00.png)
